name: HomesPlugin
version: '${project.version}'
main: me.orlogg.homesplugin.HomesPlugin
api-version: 1.19
authors: [ 0rlogg ]
description: Plugin to save and display the coordinates chosen by the user.
website: https://github.com/0rlogg
commands:
  SetHome:
    description: a
  Home:
    description: a
